## ------ Grundeinstellungen ------
server:
   port: 8080
   error:
      include-stacktrace: always
      
spring:
   application:
      name: dta-gateway
      
##------ Eureka Discovery ------
eureka:
   client:
      serviceUrl:
         defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      register-with-eureka: true
      fetch-registry: true
   instance:
      preferIpAddress: true

##------ Loadbalancing ------
ribbon:
   eureka: 
      enabled: true
      
##------ Gateway ------
security: 
   basic: 
      enabled: false
      
## https://stackoverflow.com/questions/39102980/zuul-eureka-server-basic-authentication-issue
zuul:
   sensitiveHeaders: Cookie,Set-Cookie